### PR TITLE
Add trimming facility to fastq-grep.

### PR DESCRIPTION
**Pull request by flamholz**
I added the ability to trim reads that match a regex. I had previously implemented this in python, but C is so much faster.

Let me know if it makes sense to integrate this functionality.
Avi

### CODE REVIEW

**Comment by fakeholz** [comment]
Just checking in about whether it is useful/worthwhile to integrate this.
Avi

**Comment by dcjones** [comment]
Sorry to neglect this, it would be a great addition. If you'd be so kind as to replace the the tabs with spaces in your code, to be consistent with everything else, I'll merge it.

**Comment by flamholz** [comment]
Great! I have replaced tabs with spaces. 
best,
Avi

**Comment by dcjones** [comment]
Thanks!

**Pull request merged**
